[package]
name = "porker"
version = "0.1.0"
authors = ["Kosuke Ito <ito-kosuke0502@g.ecc.u-tokyo.ac.jp>"]
edition = "2018"

[lib]
name = "porkerlib"
path = "src/lib.rs"

[[bin]]
name = "porkerbin"
path = "src/main.rs"
[dependencies]
rand = "0.6.5"
